### ISSUE TITLE
Crash on Linux

### ISSUE THREAD

**Issue by hendrikmennen** [jmacato/AvaloniaGif#3]
Hello,
Gifs work fine for me on Windows.
However on linux they appear to randomly crash the application.

```
Unhandled Exception: System.Collections.Generic.KeyNotFoundException: The given key '0' was not present in the dictionary.
   at System.Collections.Generic.SortedDictionary`2.get_Item(TKey key)
   at Avalonia.Rendering.DirtyVisuals.Add(IVisual visual)
   at AvaloniaGif.GifInstance.RenderTick(TimeSpan time)
   at Avalonia.Rendering.DefaultRenderTimer.InternalTick(TimeSpan tickCount)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.TimerQueue.FireNextTimers()

```

This happened even when there were no visible Gifs on screen

**Comment by hendrikmennen** [comment]
Also this different error
```
Unhandled Exception: System.InvalidOperationException: Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.
   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
   at Avalonia.Rendering.DirtyVisuals.Add(IVisual visual)
   at AvaloniaGif.GifInstance.RenderTick(TimeSpan time)
   at Avalonia.Rendering.DefaultRenderTimer.InternalTick(TimeSpan tickCount)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.TimerQueue.FireNextTimers()

```

**Comment by jmacato** [comment]
@HendrikMennen can you provide a sample GIF that i can test with?

**Comment by jmacato** [comment]
@HendrikMennen sorry for the super late reply, but can you give me the system info and the GIF that reproduces this bug?

**Comment by timothyparez** [comment]
I've had the same issue.  
Every now and then on Linux (Ubuntu 19.10)
and constantly on MacOS.
