### ISSUE TITLE
Compatibility with Avalonia 0.10.0?

### ISSUE THREAD

**Issue by derekantrican** [jmacato/AvaloniaGif#8]
Avalonia is getting close to releasing 0.10.0 and has published a release candidate, 0.10.0-rc1. When upgrading to this version, AvaloniaGif throws the following exception:

```
System.TypeInitializationException
  HResult=0x80131534
  Message=The type initializer for 'AvaloniaGif.GifImage' threw an exception.
  Source=Bulk Edit Calendar Events_WPF
  StackTrace:
   at Bulk_Edit_Calendar_Events_WPF.Windows.Loading.!XamlIlPopulate(IServiceProvider , Loading ) in C:\Users\derek\source\repos\derekantrican\Bulk-Edit-Calendar-Events\Bulk Edit Calendar Events_WPF\Windows/Loading.axaml:line 18
   at Bulk_Edit_Calendar_Events_WPF.Windows.Loading.!XamlIlPopulateTrampoline(Loading )
   at Bulk_Edit_Calendar_Events_WPF.Windows.Loading.InitializeComponent() in C:\Users\derek\source\repos\derekantrican\Bulk-Edit-Calendar-Events\Bulk Edit Calendar Events_WPF\Windows\Loading.axaml.cs:line 22
   at Bulk_Edit_Calendar_Events_WPF.Windows.Loading..ctor() in C:\Users\derek\source\repos\derekantrican\Bulk-Edit-Calendar-Events\Bulk Edit Calendar Events_WPF\Windows\Loading.axaml.cs:line 17
   at Bulk_Edit_Calendar_Events_WPF.Windows.Loading.ShowLoadingScreen() in C:\Users\derek\source\repos\derekantrican\Bulk-Edit-Calendar-Events\Bulk Edit Calendar Events_WPF\Windows\Loading.axaml.cs:line 38
   at Bulk_Edit_Calendar_Events_WPF.App.OnFrameworkInitializationCompleted() in C:\Users\derek\source\repos\derekantrican\Bulk-Edit-Calendar-Events\Bulk Edit Calendar Events_WPF\Windows\App.axaml.cs:line 36
   at Avalonia.Controls.AppBuilderBase`1.Setup()
   at Avalonia.Controls.AppBuilderBase`1.SetupWithLifetime(IApplicationLifetime lifetime)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode)
   at Bulk_Edit_Calendar_Events_WPF.Program.Main(String[] args) in C:\Users\derek\source\repos\derekantrican\Bulk-Edit-Calendar-Events\Bulk Edit Calendar Events_WPF\Program.cs:line 22

Inner Exception 1:
MissingMethodException: Method not found: 'Avalonia.AttachedProperty`1<!!2> Avalonia.AvaloniaProperty.RegisterAttached(System.String, !!2, Boolean, Avalonia.Data.BindingMode, System.Func`3<!!1,!!2,!!2>)'.
```

My code is like this:

```xml
<Image Grid.Column="1" HorizontalAlignment="Right" gif:GifImage.SourceStream="{Binding CalendarLoadingStream}"/>
```

```csharp
public Stream CalendarLoadingStream
{
    get
    {
        return Assembly.GetExecutingAssembly().GetManifestResourceStream("Bulk Edit Calendar Events_WPF.Resources.calendarloading.gif");
    }
}
```

I think this is due to a breaking change in how Avalonia Properties work in 0.10.0: https://github.com/AvaloniaUI/Avalonia/wiki/Breaking-Changes#avalonia-properties

**Comment by derekantrican** [comment]
0.10.0 is now released.  believe this is now the only remaining blockade to upgrading my application to 0.10.0

**Comment by B8ightY** [comment]
Same error here.. just waiting for support for 0.10.0

**Comment by derekantrican** [comment]
I may be able to figure it out and start a PR later. Just AFK right now

**Comment by B8ightY** [comment]
That would be great! If so, let me know

**Comment by derekantrican** [comment]
I just made a PR for this, but here's how you can quickly solve this yourself:

1. Open the directory where you cloned AvaloniaGif (eg `[Your Project]\external\avaloniagif`)
2. Open `AvaloniaGif.sln` in Visual Studio
3. Use Nuget Package Manager to upgrade all Avalonia references to 0.10.0 (note that you'll also have to make the `Program.cs` change as noted on the [Avalonia breaking changes list](https://github.com/AvaloniaUI/Avalonia/wiki/Breaking-Changes). Reference my PR if needed)
4. Build with Visual Studio
5. Should be good to go!
